services:
  db:
    image: postgres:latest
    container_name: postgres_container_project
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "9111:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: